#! /bin/bash

for f in cases/*/*.ttl ; do
    a=$(ls "$f")
    b=$(grep '@prefix :' "$f" | cut -c 12- | rev | cut -c 5- | rev)
    [ "$a" == "$b" ] || {
        echo "$a has an incorrect : prefix"
        exit 1
    }
done
